#:include kv/generatorscreen.kv
#:include kv/introscreen.kv
#:import NoTransition  kivy.uix.screenmanager.NoTransition
ScreenManager:
    id: screen_manager
    transition: NoTransition()
    IntroScreen:
        id: intro_screen
        name: 'intro_screen'
        manager: 'screen_manager'
    GeneratorScreen:
        id: generator_screen
        name: 'generator_screen'
        manager: 'screen_manager'